version: '3'

services:
  server:
    build:
      context: .
    stdin_open: true
    command: ["/bin/bash", "-l", "-c", "/root/Server"]
    volumes:
        - ./container-files:/root
    ports:
      - 1027:1027

